### Connect to Kaggle

We will be using data available on Kaggle platform for this exercise. The data is available at https://www.kaggle.com/c/word2vec-nlp-tutorial/data.

In [1]:
!pip uninstall tensorflow --quiet

Proceed (Y/n)? y
y

In [2]:
!pip install tensorflow==2.15.0

Collecting tensorflow==2.15.0
  Downloading tensorflow-2.15.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.15.0) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.15.0) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.15.0) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.15.0) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.15.0) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.15.0) (3.12.1)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.15.0) (18.1.1)
Collecting ml-dtypes~=0.2.0 (from tensorflow==2.15.0)
  Downloading ml_dtypes-0.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.15.0) (1.26.4)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.15.0) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.15.0) (24.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.15.0) (4.25.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.15.0) (75.1.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.15.0) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.15.0) (2.5.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.15.0) (4.12.2)
Collecting wrapt<1.15,>=1.11.0 (from tensorflow==2.15.0)
  Downloading wrapt-1.14.1-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.15.0) (0.37.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow==2.15.0) (1.71.0)
Collecting tensorboard<2.16,>=2.15 (from tensorflow==2.15.0)
  Downloading tensorboard-2.15.2-py3-none-any.whl.metadata (1.7 kB)
Collecting tensorflow-estimator<2.16,>=2.15.0 (from tensorflow==2.15.0)
  Downloading tensorflow_estimator-2.15.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting keras<2.16,>=2.15.0 (from tensorflow==2.15.0)
  Downloading keras-2.15.0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from astunparse>=1.6.0->tensorflow==2.15.0) (0.45.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.16,>=2.15->tensorflow==2.15.0) (2.38.0)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.16,>=2.15->tensorflow==2.15.0) (1.2.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.16,>=2.15->tensorflow==2.15.0) (3.7)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.16,>=2.15->tensorflow==2.15.0) (2.32.3)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.16,>=2.15->tensorflow==2.15.0) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from tensorboard<2.16,>=2.15->tensorflow==2.15.0) (3.1.3)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (2.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (2025.1.31)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.11/dist-packages (from werkzeug>=1.0.1->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (3.0.2)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (0.6.1)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow==2.15.0) (3.2.2)
Downloading tensorflow-2.15.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (475.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 475.3/475.3 MB 1.3 MB/s eta 0:00:00
Downloading keras-2.15.0-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 55.8 MB/s eta 0:00:00
Downloading ml_dtypes-0.2.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 40.4 MB/s eta 0:00:00
Downloading tensorboard-2.15.2-py3-none-any.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 41.3 MB/s eta 0:00:00
Downloading tensorflow_estimator-2.15.0-py2.py3-none-any.whl (441 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.0/442.0 kB 33.3 MB/s eta 0:00:00
Downloading wrapt-1.14.1-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 8.3 MB/s eta 0:00:00
Installing collected packages: wrapt, tensorflow-estimator, ml-dtypes, keras, tensorboard, tensorflow
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.17.2
    Uninstalling wrapt-1.17.2:
      Successfully uninstalled wrapt-1.17.2
  Attempting uninstall: ml-dtypes
    Found existing installation: ml-dtypes 0.4.1
    Uninstalling ml-dtypes-0.4.1:
      Successfully uninstalled ml-dtypes-0.4.1
  Attempting uninstall: keras
    Found existing installation: keras 3.8.0
    Uninstalling keras-3.8.0:
      Successfully uninstalled keras-3.8.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.18.0
    Uninstalling tensorboard-2.18.0:
      Successfully uninstalled tensorboard-2.18.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jax 0.5.2 requires ml_dtypes>=0.4.0, but you have ml-dtypes 0.2.0 which is incompatible.
tensorflow-text 2.18.1 requires tensorflow<2.19,>=2.18.0, but you have tensorflow 2.15.0 which is incompatible.
tf-keras 2.18.0 requires tensorflow<2.19,>=2.18, but you have tensorflow 2.15.0 which is incompatible.
tensorstore 0.1.72 requires ml_dtypes>=0.3.1, but you have ml-dtypes 0.2.0 which is incompatible.
Successfully installed keras-2.15.0 ml-dtypes-0.2.0 tensorboard-2.15.2 tensorflow-2.15.0 tensorflow-estimator-2.15.0 wrapt-1.14.1

In [3]:
#Connect Google drive to colab
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive

### 1. Import the dataset as pandas dataframe

In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('/gdrive/MyDrive/HGN/NLP By HGN/NLP for SRM /HGN/Unit 3/Notebooks/1. Text Classification with RNN/labeledTrainData.tsv.zip',header=0, delimiter="\t", quoting=3)

In [6]:
df.shape

(25000, 3)

In [7]:
df.head()

         id  sentiment                                             review
0  "5814_8"          1  "With all this stuff going down at the moment ...
1  "2381_9"          1  "\"The Classic War of the Worlds\" by Timothy ...
2  "7759_3"          0  "The film starts with a manager (Nicholas Bell...
3  "3630_4"          0  "It must be assumed that those who praised thi...
4  "9495_8"          1  "Superbly trashy and wondrously unpretentious ...

In [8]:
df.groupby(['sentiment']).count()

              id  review
sentiment
0          12500   12500
1          12500   12500

In [9]:
df.loc[1500, 'review']

'"Well I gave this movie a 7. It was better than \\"Thirdspace\\" but not as good as \\"In the Beginning\\" as far as the B5 movies go. I really think the television series did a much better job overall with the special effects and character portrayal. Let\'s hope the producers and cast get the next series \\"Crusade\\" up to the standards of B5."'

#### Split Data into Training and Test Data

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
train, test = train_test_split(df, test_size=0.2, random_state=42)

In [12]:
train.shape, test.shape

((20000, 3), (5000, 3))

In [13]:
train.reset_index(inplace=True, drop=True)
test.reset_index(inplace=True, drop=True)

In [14]:
X_train = train['review']
y_train = train['sentiment']

In [15]:
X_test = test['review']
y_test = test['sentiment']

### 2. Build the Tokenizer

In [16]:
import tensorflow as tf

In [17]:
desired_vocab_size = 30000 #Vocablury size
t = tf.keras.preprocessing.text.Tokenizer(num_words=desired_vocab_size) # num_words -> Vocablury size

In [18]:
#Fit tokenizer with actual training data
t.fit_on_texts(X_train.tolist())

In [19]:
len(t.word_index)

79965

In [20]:
#Vocabulary
print(t.word_index)

{'the': 1, 'and': 2, 'a': 3, 'of': 4, 'to': 5, 'is': 6, 'br': 7, 'in': 8, 'it': 9, 'i': 10, 'this': 11, 'that': 12, 'was': 13, 'as': 14, 'for': 15, 'with': 16, 'movie': 17, 'but': 18, 'film': 19, 'on': 20, 'not': 21, 'you': 22, 'his': 23, 'are': 24, 'have': 25, 'he': 26, 'be': 27, 'one': 28, 'all': 29, 'at': 30, 'by': 31, 'an': 32, 'they': 33, 'who': 34, 'so': 35, 'from': 36, 'like': 37, 'her': 38, 'or': 39, 'just': 40, 'about': 41, "it's": 42, 'out': 43, 'has': 44, 'if': 45, 'there': 46, 'some': 47, 'what': 48, 'good': 49, 'more': 50, 'when': 51, 'very': 52, 'up': 53, 'no': 54, 'even': 55, 'time': 56, 'she': 57, 'my': 58, 'would': 59, 'which': 60, 'only': 61, 'story': 62, 'really': 63, 'see': 64, 'had': 65, 'their': 66, 'can': 67, 'me': 68, 'were': 69, 'well': 70, 'than': 71, 'we': 72, 'much': 73, 'get': 74, 'been': 75, 'bad': 76, 'will': 77, 'also': 78, 'do': 79, 'into': 80, 'other': 81, 'great': 82, 'first': 83, 'people': 84, 'because': 85, 'him': 86, 'how': 87, 'most': 88, "don't": 89, 'made': 90, 'then': 91, 'its': 92, 'make': 93, 'way': 94, 'them': 95, 'could': 96, 'too': 97, 'any': 98, 'after': 99, 'movies': 100, 'think': 101, 'characters': 102, 'watch': 103, 'two': 104, 'films': 105, 'seen': 106, 'character': 107, 'many': 108, 'being': 109, 'plot': 110, 'life': 111, 'acting': 112, 'never': 113, 'little': 114, 'best': 115, 'love': 116, 'where': 117, 'over': 118, 'did': 119, 'know': 120, 'show': 121, 'off': 122, 'ever': 123, 'does': 124, 'better': 125, 'man': 126, 'end': 127, 'your': 128, 'still': 129, 'here': 130, 'scene': 131, 'say': 132, 'these': 133, 'why': 134, 'while': 135, 'scenes': 136, 'such': 137, 'something': 138, 'go': 139, 'should': 140, 'through': 141, 'back': 142, 'real': 143, "i'm": 144, 'those': 145, 'watching': 146, 'though': 147, 'now': 148, "doesn't": 149, 'thing': 150, 'years': 151, 'old': 152, 'actors': 153, '10': 154, 'before': 155, 'another': 156, 'work': 157, 'new': 158, 'actually': 159, "didn't": 160, 'nothing': 161, 'funny': 162, 'makes': 163, 'look': 164, 'director': 165, 'few': 166, 'find': 167, 'going': 168, 'same': 169, 'again': 170, 'every': 171, 'lot': 172, 'part': 173, 'cast': 174, 'quite': 175, 'us': 176, 'pretty': 177, 'around': 178, 'down': 179, 'world': 180, 'things': 181, 'seems': 182, 'young': 183, 'want': 184, "can't": 185, 'got': 186, 'fact': 187, 'horror': 188, 'take': 189, 'however': 190, 'enough': 191, 'long': 192, 'both': 193, 'thought': 194, 'action': 195, 'may': 196, 'big': 197, "i've": 198, 'between': 199, 'give': 200, 'series': 201, "that's": 202, 'own': 203, 'original': 204, 'right': 205, 'without': 206, 'must': 207, 'comedy': 208, 'always': 209, 'point': 210, 'saw': 211, 'role': 212, 'come': 213, "isn't": 214, 'gets': 215, 'times': 216, 'least': 217, 'done': 218, 'almost': 219, 'interesting': 220, "there's": 221, 'bit': 222, 'family': 223, 'whole': 224, 'music': 225, 'guy': 226, 'script': 227, 'far': 228, 'feel': 229, 'anything': 230, 'making': 231, 'since': 232, 'minutes': 233, "he's": 234, 'might': 235, 'last': 236, 'performance': 237, 'probably': 238, '2': 239, 'kind': 240, 'away': 241, 'worst': 242, 'yet': 243, 'tv': 244, 'am': 245, 'rather': 246, 'girl': 247, 'sure': 248, 'hard': 249, 'day': 250, 'woman': 251, 'fun': 252, 'found': 253, 'although': 254, 'played': 255, 'anyone': 256, 'each': 257, 'having': 258, 'especially': 259, 'course': 260, 'looking': 261, 'believe': 262, 'our': 263, 'comes': 264, 'screen': 265, 'trying': 266, 'book': 267, 'set': 268, 'put': 269, 'place': 270, 'goes': 271, 'looks': 272, 'reason': 273, 'maybe': 274, 'ending': 275, 'money': 276, 'different': 277, 'true': 278, 'actor': 279, 'once': 280, 'sense': 281, 'dvd': 282, 'everything': 283, 'year': 284, 'shows': 285, 'main': 286, 'someone': 287, 'job': 288, "wasn't": 289, 'together': 290, 'worth': 291, 'three': 292, 'watched': 293, 'plays': 294, 'seem': 295, 'instead': 296, 'play': 297, 'said': 298, 'later': 299, 'house': 300, 'american': 301, 'takes': 302, 'effects': 303, '1': 304, 'left': 305, 'john': 306, 'audience': 307, 'himself': 308, 'version': 309, 'everyone': 310, 'during': 311, 'night': 312, 'high': 313, 'beautiful': 314, 'star': 315, 'seeing': 316, 'war': 317, 'special': 318, 'half': 319, 'idea': 320, 'wife': 321, 'excellent': 322, 'shot': 323, 'mind': 324, 'nice': 325, 'second': 326, 'less': 327, 'else': 328, 'simply': 329, 'father': 330, 'black': 331, 'read': 332, 'help': 333, 'death': 334, 'completely': 335, 'men': 336, "you're": 337, 'home': 338, 'short': 339, 'poor': 340, 'fan': 341, '3': 342, 'given': 343, 'either': 344, 'wrong': 345, 'used': 346, 'line': 347, 'dead': 348, 'need': 349, 'top': 350, 'boring': 351, 'kids': 352, 'try': 353, 'enjoy': 354, 'rest': 355, 'budget': 356, 'women': 357, 'classic': 358, 'performances': 359, 'low': 360, 'production': 361, 'hollywood': 362, 'along': 363, 'use': 364, 'full': 365, 'until': 366, 'friends': 367, 'awful': 368, 'camera': 369, 'video': 370, 'next': 371, 'start': 372, 'tell': 373, 'truly': 374, 'sex': 375, 'moments': 376, 'stupid': 377, 'mean': 378, 'stars': 379, 'came': 380, 'perhaps': 381, 'remember': 382, 'recommend': 383, 'getting': 384, 'small': 385, 'let': 386, 'couple': 387, 'understand': 388, 'wonderful': 389, 'school': 390, 'written': 391, 'perfect': 392, 'face': 393, 'terrible': 394, 'episode': 395, 'playing': 396, 'name': 397, 'keep': 398, 'style': 399, 'doing': 400, 'early': 401, 'definitely': 402, 'often': 403, 'gives': 404, 'others': 405, 'human': 406, 'lines': 407, 'become': 408, 'felt': 409, 'dialogue': 410, 'piece': 411, 'head': 412, 'itself': 413, 'lost': 414, 'person': 415, 'live': 416, 'finally': 417, 'liked': 418, 'supposed': 419, 'yes': 420, "couldn't": 421, 'boy': 422, 'case': 423, 'title': 424, 'against': 425, 'worse': 426, 'sort': 427, 'went': 428, 'cinema': 429, 'white': 430, 'entire': 431, 'picture': 432, 'evil': 433, 'mr': 434, 'certainly': 435, 'entertaining': 436, 'oh': 437, 'absolutely': 438, 'hope': 439, 'problem': 440, "she's": 441, 'beginning': 442, 'called': 443, 'overall': 444, 'waste': 445, 'fans': 446, 'killer': 447, 'drama': 448, 'mother': 449, 'laugh': 450, 'based': 451, 'loved': 452, 'several': 453, '5': 454, 'direction': 455, 'care': 456, 'under': 457, 'turn': 458, 'despite': 459, 'example': 460, 'already': 461, 'unfortunately': 462, 'friend': 463, 'becomes': 464, "i'd": 465, 'throughout': 466, 'children': 467, 'dark': 468, 'heart': 469, 'seemed': 470, '4': 471, 'wanted': 472, 'totally': 473, '\x96': 474, 'final': 475, 'lives': 476, 'guys': 477, 'lead': 478, 'humor': 479, 'quality': 480, 'amazing': 481, 'history': 482, 'sound': 483, 'son': 484, 'wants': 485, "you'll": 486, 'art': 487, 'guess': 488, 'b': 489, 'writing': 490, 'close': 491, 'able': 492, 'tries': 493, 'fine': 494, 'flick': 495, 'past': 496, 'side': 497, 'days': 498, 'behind': 499, 'turns': 500, 'game': 501, 'hand': 502, 'sometimes': 503, 'works': 504, 'soon': 505, 'kill': 506, 'gave': 507, 'eyes': 508, 'etc': 509, 'enjoyed': 510, 'genre': 511, 'horrible': 512, 'favorite': 513, 'directed': 514, "won't": 515, 'run': 516, 'starts': 517, 'child': 518, 'viewer': 519, "they're": 520, 'michael': 521, 'town': 522, 'act': 523, 'car': 524, 'late': 525, 'expect': 526, 'obviously': 527, 'thinking': 528, 'themselves': 529, 'actress': 530, 'blood': 531, 'stuff': 532, 'decent': 533, 'except': 534, 'voice': 535, 'anyway': 536, 'brilliant': 537, 'hour': 538, 'city': 539, 'self': 540, 'parts': 541, 'highly': 542, 'feeling': 543, 'fight': 544, 'stories': 545, 'myself': 546, 'girls': 547, 'moment': 548, 'roles': 549, 'says': 550, 'heard': 551, 'kid': 552, 'matter': 553, 'killed': 554, 'type': 555, 'leave': 556, 'violence': 557, 'strong': 558, 'particularly': 559, 'age': 560, 'took': 561, 'slow': 562, 'happened': 563, 'cannot': 564, 'police': 565, 'obvious': 566, 'please': 567, 'writer': 568, 'known': 569, "wouldn't": 570, 'stop': 571, 'living': 572, 'daughter': 573, 's': 574, 'hit': 575, 'murder': 576, 'cut': 577, 'god': 578, 'happens': 579, 'brother': 580, 'extremely': 581, 'lack': 582, 'experience': 583, 'involved': 584, 'happen': 585, 'coming': 586, 'score': 587, 'chance': 588, 'wonder': 589, 'hell': 590, 'told': 591, 'crap': 592, 'simple': 593, 'save': 594, 'including': 595, 'james': 596, 'alone': 597, 'gore': 598, "film's": 599, 'number': 600, 'group': 601, 'attempt': 602, 'career': 603, 'possible': 604, 'ok': 605, 'seriously': 606, 'none': 607, 'scary': 608, 'released': 609, 'complete': 610, 'ago': 611, 'looked': 612, 'cinematography': 613, 'interest': 614, 'song': 615, 'opening': 616, 'taken': 617, 'jokes': 618, 'usually': 619, 'shown': 620, 'hilarious': 621, 'exactly': 622, 'musical': 623, 'running': 624, 'reality': 625, "i'll": 626, 'sad': 627, 'light': 628, 'ends': 629, 'whose': 630, 'body': 631, 'cool': 632, 'yourself': 633, 'somewhat': 634, 'today': 635, 'level': 636, 'ridiculous': 637, 'view': 638, 'room': 639, 'english': 640, 'started': 641, 'across': 642, 'annoying': 643, 'relationship': 644, 'robert': 645, 'opinion': 646, 'hours': 647, 'wish': 648, 'female': 649, 'david': 650, 'order': 651, 'serious': 652, 'talking': 653, 'finds': 654, 'novel': 655, 'talent': 656, 'ones': 657, 'taking': 658, 'usual': 659, 'hero': 660, 'word': 661, 'happy': 662, 'husband': 663, 'change': 664, 'call': 665, 'middle': 666, 'shots': 667, 'power': 668, 'mostly': 669, 'events': 670, 'five': 671, 'strange': 672, '7': 673, 'apparently': 674, 'huge': 675, 'important': 676, 'rating': 677, 'documentary': 678, 'non': 679, 'future': 680, 'disappointed': 681, 'knows': 682, 'saying': 683, 'modern': 684, 'basically': 685, 'single': 686, 'due': 687, 'knew': 688, 'supporting': 689, 'episodes': 690, 'major': 691, 'tells': 692, 'clearly': 693, 'attention': 694, 'sequence': 695, 'thriller': 696, 'four': 697, 'television': 698, 'songs': 699, 'comic': 700, 'turned': 701, 'jack': 702, 'country': 703, 'fast': 704, 'british': 705, 'words': 706, 'class': 707, 'bring': 708, '8': 709, 'silly': 710, 'earth': 711, 'miss': 712, 'paul': 713, 'romantic': 714, 'whether': 715, 'easily': 716, 'straight': 717, 'king': 718, 'animation': 719, "aren't": 720, 'upon': 721, 'oscar': 722, 'problems': 723, 'beyond': 724, 'cheap': 725, 'enjoyable': 726, 'review': 727, 'needs': 728, 'eye': 729, 'mystery': 730, 'local': 731, 'entertainment': 732, 'talk': 733, 'moving': 734, 'predictable': 735, 'rock': 736, 'ten': 737, 'dull': 738, 'giving': 739, 'appears': 740, 'falls': 741, 'points': 742, 'similar': 743, 'message': 744, 'theater': 745, 'add': 746, 'hate': 747, 'sets': 748, 'begins': 749, 'near': 750, 'sister': 751, 'theme': 752, 'george': 753, 'herself': 754, 'release': 755, 'bunch': 756, 'mention': 757, 'stand': 758, 'using': 759, 'within': 760, 'above': 761, 'red': 762, 'lady': 763, 'richard': 764, 'die': 765, "haven't": 766, 'lots': 767, 'storyline': 768, 'surprised': 769, 'clear': 770, 'feels': 771, 'french': 772, 'showing': 773, 'actual': 774, 'tale': 775, 'named': 776, 'stay': 777, 'fantastic': 778, 'sequel': 779, 'tried': 780, 'easy': 781, 'feature': 782, 'follow': 783, 'weak': 784, 'york': 785, 'ways': 786, 'working': 787, 'sorry': 788, 'comments': 789, 'team': 790, 'period': 791, 'nearly': 792, "what's": 793, 'season': 794, 'filmed': 795, 'figure': 796, 'gone': 797, 'check': 798, "'": 799, 'certain': 800, 'minute': 801, 'effort': 802, 'material': 803, 're': 804, 'leads': 805, 'somehow': 806, 'among': 807, 'peter': 808, 'editing': 809, 'famous': 810, 'means': 811, 'viewers': 812, 'dialog': 813, 'elements': 814, '9': 815, 'soundtrack': 816, 'doubt': 817, 'general': 818, 'sequences': 819, 'avoid': 820, 'greatest': 821, 'form': 822, 'fall': 823, 'tom': 824, 'brought': 825, 'suspense': 826, 'viewing': 827, 'realistic': 828, 'particular': 829, 'buy': 830, 'typical': 831, 'space': 832, 'kept': 833, 'imagine': 834, 'forget': 835, 'third': 836, 'dance': 837, 'crime': 838, 'lame': 839, 'note': 840, 'whatever': 841, 'poorly': 842, 'lee': 843, 'atmosphere': 844, 'learn': 845, 'hear': 846, 't': 847, 'rent': 848, 'move': 849, 'expected': 850, 'average': 851, 'needed': 852, 'wait': 853, 'believable': 854, 'sit': 855, 'indeed': 856, 'parents': 857, 'street': 858, 'possibly': 859, 'became': 860, 'stage': 861, 'deal': 862, 'decided': 863, 'reading': 864, 'otherwise': 865, 'eventually': 866, 'nature': 867, 'screenplay': 868, 'de': 869, 'meets': 870, 'sexual': 871, 'surprise': 872, 'premise': 873, 'subject': 874, 'free': 875, "you've": 876, "who's": 877, 'hot': 878, 'baby': 879, 'joe': 880, '20': 881, 'killing': 882, 'disney': 883, 'nor': 884, "let's": 885, 'leaves': 886, 'romance': 887, 'okay': 888, 'question': 889, 'reviews': 890, 'begin': 891, 'credits': 892, 'dramatic': 893, 'society': 894, 'difficult': 895, 'shame': 896, 'forward': 897, 'male': 898, 'write': 899, 'laughs': 900, 'meet': 901, 'memorable': 902, 'unless': 903, 'truth': 904, 'perfectly': 905, 'realize': 906, 'zombie': 907, 'dr': 908, 'japanese': 909, 'earlier': 910, 'crazy': 911, 'superb': 912, 'sounds': 913, 'interested': 914, 'directors': 915, 'badly': 916, 'writers': 917, 'dream': 918, 'air': 919, 'open': 920, 'imdb': 921, 'footage': 922, 'powerful': 923, 'forced': 924, 'development': 925, 'situation': 926, 'emotional': 927, 'monster': 928, 'beauty': 929, 'worked': 930, 'fantasy': 931, 'acted': 932, 'whom': 933, 'directing': 934, 'older': 935, 'deep': 936, 'incredibly': 937, 'weird': 938, 'america': 939, 'quickly': 940, 'hands': 941, 'effect': 942, 'box': 943, 'joke': 944, 'brings': 945, 'leading': 946, 'plus': 947, 'political': 948, 'cheesy': 949, 'total': 950, 'towards': 951, 'mark': 952, 'sci': 953, 'comment': 954, 'admit': 955, 'mess': 956, 'ask': 957, 'fi': 958, 'fighting': 959, 'background': 960, 'cop': 961, 'appear': 962, 'setting': 963, 'creepy': 964, 'previous': 965, 'plenty': 966, 'battle': 967, 'rate': 968, 'e': 969, 'front': 970, 'personal': 971, 'unique': 972, 'dumb': 973, 'result': 974, 'present': 975, 'casting': 976, 'masterpiece': 977, 'return': 978, 'fire': 979, 'potential': 980, 'fails': 981, 'deserves': 982, 'features': 983, 'expecting': 984, 'various': 985, 'create': 986, 'reasons': 987, 'nudity': 988, 'apart': 989, 'match': 990, 'dog': 991, 'keeps': 992, 'business': 993, 'gay': 994, 'list': 995, 'married': 996, 'co': 997, 'outside': 998, 'inside': 999, 'hardly': 1000, 'telling': 1001, 'villain': 1002, 'bill': 1003, 'western': 1004, 'recently': 1005, 'meant': 1006, 'girlfriend': 1007, 'twist': 1008, 'break': 1009, 'pay': 1010, 'agree': 1011, 'missing': 1012, 'boys': 1013, 'success': 1014, 'social': 1015, 'unlike': 1016, 'cute': 1017, 'ideas': 1018, 'doctor': 1019, 'ben': 1020, 'remake': 1021, 'attempts': 1022, 'cold': 1023, 'rich': 1024, 'fairly': 1025, 'secret': 1026, 'portrayed': 1027, 'wrote': 1028, 'jane': 1029, 'flat': 1030, 'christmas': 1031, 'odd': 1032, 'era': 1033, 'filled': 1034, 'mentioned': 1035, 'talented': 1036, 'gun': 1037, 'filmmakers': 1038, 'william': 1039, 'further': 1040, 'missed': 1041, 'sweet': 1042, 'decides': 1043, 'public': 1044, 'copy': 1045, 'spoilers': 1046, 'party': 1047, 'office': 1048, 'large': 1049, 'pace': 1050, 'caught': 1051, 'la': 1052, 'created': 1053, 'incredible': 1054, 'pure': 1055, 'waiting': 1056, 'sadly': 1057, 'plain': 1058, 'sees': 1059, 'laughing': 1060, 'fear': 1061, 'revenge': 1062, 'd': 1063, 'cartoon': 1064, 'members': 1065, 'ended': 1066, 'brothers': 1067, 'crew': 1068, 'popular': 1069, 'manages': 1070, 'moves': 1071, 'wasted': 1072, 'choice': 1073, 'considering': 1074, 'slightly': 1075, 'neither': 1076, "we're": 1077, 'spent': 1078, 'dancing': 1079, 'tension': 1080, 'escape': 1081, 'violent': 1082, 'convincing': 1083, 'following': 1084, 'bored': 1085, 'uses': 1086, 'value': 1087, 'compared': 1088, 'italian': 1089, '6': 1090, 'visual': 1091, 'clever': 1092, 'produced': 1093, 'german': 1094, 'century': 1095, 'suddenly': 1096, 'science': 1097, 'adult': 1098, 'entirely': 1099, 'hold': 1100, 'kills': 1101, 'successful': 1102, 'trouble': 1103, 'force': 1104, 'control': 1105, 'state': 1106, 'mary': 1107, 'animated': 1108, 'spirit': 1109, "'the": 1110, 'exciting': 1111, 'biggest': 1112, '30': 1113, 'runs': 1114, 'younger': 1115, 'cat': 1116, 'solid': 1117, 'speak': 1118, 'depth': 1119, 'former': 1120, 'appreciate': 1121, 'store': 1122, 'effective': 1123, 'studio': 1124, 'died': 1125, 'spend': 1126, 'band': 1127, 'recent': 1128, 'ultimately': 1129, '15': 1130, 'scott': 1131, 'cover': 1132, 'intelligent': 1133, 'familiar': 1134, 'singing': 1135, 'language': 1136, 'producers': 1137, 'trash': 1138, 'rated': 1139, 'fit': 1140, 'van': 1141, 'concept': 1142, 'amusing': 1143, 'zombies': 1144, 'credit': 1145, 'respect': 1146, 'books': 1147, 'c': 1148, 'island': 1149, 'focus': 1150, 'f': 1151, 'bizarre': 1152, 'tone': 1153, 'project': 1154, 'pointless': 1155, 'shooting': 1156, 'follows': 1157, 'considered': 1158, 'walk': 1159, 'portrayal': 1160, 'college': 1161, 'basic': 1162, 'mad': 1163, 'starring': 1164, 'win': 1165, 'adventure': 1166, 'decide': 1167, 'somewhere': 1168, 'heavy': 1169, 'cause': 1170, 'hair': 1171, 'showed': 1172, 'impossible': 1173, 'changed': 1174, 'won': 1175, 'law': 1176, 'makers': 1177, 'positive': 1178, 'disturbing': 1179, 'sick': 1180, 'tony': 1181, 'common': 1182, 'surprisingly': 1183, 'prison': 1184, 'honest': 1185, 'slasher': 1186, 'water': 1187, 'charming': 1188, 'questions': 1189, 'barely': 1190, 'company': 1191, 'yeah': 1192, 'likes': 1193, 'impressive': 1194, 'meaning': 1195, 'frank': 1196, 'conclusion': 1197, 'consider': 1198, 'involving': 1199, 'aside': 1200, 'tough': 1201, 'stick': 1202, 'audiences': 1203, 'accent': 1204, 'super': 1205, 'dad': 1206, 'natural': 1207, 'anti': 1208, 'post': 1209, "weren't": 1210, 'grade': 1211, 'leaving': 1212, 'camp': 1213, 'situations': 1214, 'computer': 1215, 'culture': 1216, 'recommended': 1217, 'chemistry': 1218, '100': 1219, 'amount': 1220, 'pick': 1221, 'failed': 1222, 'values': 1223, 'u': 1224, 'trip': 1225, 'cult': 1226, 'generally': 1227, 'awesome': 1228, 'brain': 1229, 'fiction': 1230, 'south': 1231, 'fake': 1232, 'detective': 1233, 'longer': 1234, 'planet': 1235, 'thanks': 1236, 'attack': 1237, 'images': 1238, 'sitting': 1239, 'steve': 1240, 'honestly': 1241, 'pathetic': 1242, 'catch': 1243, 'standard': 1244, 'appeal': 1245, 'military': 1246, 'literally': 1247, 'bought': 1248, 'utterly': 1249, 'explain': 1250, 'appearance': 1251, 'normal': 1252, 'ex': 1253, 'touch': 1254, 'glad': 1255, 'sexy': 1256, 'walking': 1257, 'shoot': 1258, 'naked': 1259, 'harry': 1260, 'adaptation': 1261, 'west': 1262, 'nowhere': 1263, 'army': 1264, 'thank': 1265, 'jim': 1266, 'loud': 1267, 'pictures': 1268, 'aspect': 1269, 'rare': 1270, 'equally': 1271, 'alive': 1272, 'drive': 1273, 'humour': 1274, 'drawn': 1275, 'ghost': 1276, 'magic': 1277, 'motion': 1278, 'pieces': 1279, 'master': 1280, 'purpose': 1281, 'thinks': 1282, 'edge': 1283, 'knowing': 1284, 'managed': 1285, 'issues': 1286, 'garbage': 1287, 'genius': 1288, 'touching': 1289, 'channel': 1290, 'wild': 1291, 'key': 1292, 'chase': 1293, 'week': 1294, 'chris': 1295, 'fair': 1296, 'outstanding': 1297, 'unbelievable': 1298, 'fully': 1299, 'complex': 1300, 'road': 1301, 'terrific': 1302, 'beautifully': 1303, 'ability': 1304, 'journey': 1305, 'personally': 1306, 'twists': 1307, 'subtle': 1308, 'dreams': 1309, 'nobody': 1310, 'soldiers': 1311, 'government': 1312, 'immediately': 1313, 'taste': 1314, 'comedies': 1315, 'disappointing': 1316, 'date': 1317, 'remains': 1318, 'christopher': 1319, 'details': 1320, 'club': 1321, "movie's": 1322, 'spoiler': 1323, 'london': 1324, 'smith': 1325, 'added': 1326, 'stewart': 1327, 'justice': 1328, 'g': 1329, 'terms': 1330, 'laughable': 1331, 'mood': 1332, 'batman': 1333, 'emotion': 1334, 'surely': 1335, 'sam': 1336, 'door': 1337, 'wow': 1338, 'vampire': 1339, 'bottom': 1340, "80's": 1341, 'manner': 1342, 'plan': 1343, 'narrative': 1344, 'presence': 1345, 'themes': 1346, 'besides': 1347, 'pass': 1348, 'thrown': 1349, 'constantly': 1350, 'hoping': 1351, 'climax': 1352, 'award': 1353, 'stunning': 1354, 'aspects': 1355, 'minor': 1356, 'pr

# Prepare Training and Test Data

Get the word index for each of the word in the review

In [21]:
X_train[0]

'"This movie is just plain dumb.<br /><br />From the casting of Ralph Meeker as Mike Hammer to the fatuous climax, the film is an exercise in wooden predictability.<br /><br />Mike Hammer is one of detective fiction\'s true sociopaths. Unlike Marlow and Spade, who put pieces together to solve the mystery, Hammer breaks things apart to get to the truth. This film turns Hammer into a boob by surrounding him with bad guys who are ... well, too dumb to get away with anything. One is so poorly drawn that he succumbs to a popcorn attack.<br /><br />Other parts of the movie are right out of the Three Stooges play book. Velda\'s dance at the barre, for instance, or the bad guy who accidentally stabs his boss in the back. And the continuity breaks are shameful: Frau Blucher is running down the centerline of the road when the camera is tight on her lower legs but she\'s way over the side when the camera pulls back for a wider shot. The worst break, however, precedes the popcorn attack. The bad guy stalking Hammer passes a clock seconds after our hero, except the clock shows he was seven minutes behind our guy.<br /><br />To be fair, there were some interesting camera angles and lighting, and the grand finale is so bad that it must been seen, which is the only reason that it gets two points out of 10."'

In [22]:
X_train = t.texts_to_sequences(X_train.tolist())

In [23]:
print(X_train[0])

[11, 17, 6, 40, 1058, 973, 7, 7, 36, 1, 976, 4, 2844, 12953, 14, 1855, 4246, 5, 1, 22503, 1352, 1, 19, 6, 32, 3232, 8, 1604, 8652, 7, 7, 1855, 4246, 6, 28, 4, 1233, 278, 24570, 1016, 2, 7945, 34, 269, 1279, 290, 5, 3351, 1, 730, 4246, 2000, 181, 989, 5, 74, 5, 1, 904, 11, 19, 500, 4246, 80, 3, 9824, 31, 3467, 86, 16, 76, 477, 34, 24, 70, 97, 973, 5, 74, 241, 16, 230, 28, 6, 35, 842, 1275, 12, 26, 16192, 5, 3, 3693, 1237, 7, 7, 81, 541, 4, 1, 17, 24, 205, 43, 4, 1, 292, 4877, 297, 267, 837, 30, 1, 15, 1844, 39, 1, 76, 226, 34, 2553, 8104, 23, 1426, 8, 1, 142, 2, 1, 2348, 2000, 24, 8105, 6, 624, 179, 1, 4, 1, 1301, 51, 1, 369, 6, 2636, 20, 38, 2367, 2975, 18, 441, 94, 118, 1, 497, 51, 1, 369, 2602, 142, 15, 3, 6451, 323, 1, 242, 1009, 190, 15425, 1, 3693, 1237, 1, 76, 226, 5899, 4246, 3856, 3, 6664, 1558, 99, 263, 660, 534, 1, 6664, 285, 26, 13, 1511, 233, 499, 263, 226, 7, 7, 5, 27, 1296, 46, 69, 47, 220, 369, 2425, 2, 1536, 2, 1, 1696, 1976, 6, 35, 76, 12, 9, 207, 75, 106, 60, 6, 1, 61, 273, 12, 9, 215, 104, 742, 43, 4, 154]

In [24]:
t.sequences_to_texts([X_train[0]])

["this movie is just plain dumb br br from the casting of ralph meeker as mike hammer to the fatuous climax the film is an exercise in wooden predictability br br mike hammer is one of detective true sociopaths unlike and spade who put pieces together to solve the mystery hammer breaks things apart to get to the truth this film turns hammer into a boob by surrounding him with bad guys who are well too dumb to get away with anything one is so poorly drawn that he succumbs to a popcorn attack br br other parts of the movie are right out of the three stooges play book dance at the for instance or the bad guy who accidentally stabs his boss in the back and the continuity breaks are shameful is running down the of the road when the camera is tight on her lower legs but she's way over the side when the camera pulls back for a wider shot the worst break however precedes the popcorn attack the bad guy stalking hammer passes a clock seconds after our hero except the clock shows he was seven minutes behind our guy br br to be fair there were some interesting camera angles and lighting and the grand finale is so bad that it must been seen which is the only reason that it gets two points out of 10"]

In [25]:
X_test = t.texts_to_sequences(X_test.tolist())

How many words in each review?

In [28]:
len(X_train[2000])

377

#### Pad Sequences - Important

In [29]:
#Define maximum number of words to consider in each review
max_review_length = 300

In [30]:
#Pad training and test reviews
X_train = tf.keras.preprocessing.sequence.pad_sequences(X_train,
                                                        maxlen=max_review_length,
                                                        padding='pre',
                                                        truncating='post')

X_test = tf.keras.preprocessing.sequence.pad_sequences(X_test,
                                                       maxlen=max_review_length,
                                                       padding='pre',
                                                       truncating='post')

In [31]:
X_train.shape

(20000, 300)

In [32]:
X_test.shape

(5000, 300)

In [33]:
X_train[200]

array([    0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,    10,   211,    11,    17,    16,     3,
         756,     4,   367,     2,   254,    61,   104,     4,   176,
        2571,    43,     4,     1,   429,   528,    87,   632,     9,
          13,     1,   405,    40,  1469,     2,  4209,    20,    87,
         377,     9,    13,    70,    12,    13,    85,     9,   214,
         419,     5,    27,   617,    35,   606,   685,     9,     6,
           3,     3,    17,    12, 18297,   188,  1559,     2,   124,
           3,  1505,    49,   288,    46,   182,     5,    27,   156,
          17,   586,    43,    37,    12,    97, 17217,   608,    17,
          70,    11,     6,  6483,     2,   204,  2839, 15508,   124,
           3,   237,     2,  2744,    44,     3,  1932,   680,     8,
         112,    10,   439,     5,    64,    50,     4,    95,  4733,
       11692,    13,     3,    49,   849,     2, 18298,    13,    32,
          55,   125,   849,     1,  1173,  2489,    13,  1615,     4,
           1,   265,    10,   383,   316,    11,   495,    14,   486,
          27,  3155,   366,     1,    52,   127,     1,  2002,    16,
       27404, 10679,     2,     1,    17,    12,   113,   186,  1709,
         881,   151,   611], dtype=int32)

### 3. Build the Graph

In [34]:
#Initialize model
tf.keras.backend.clear_session()
model = tf.keras.Sequential()

Add Embedding layer
 - Embedding Layer Input = Batch_Size * Length of each review

In [35]:
model.add(tf.keras.layers.Embedding(desired_vocab_size + 1, #Vocablury size
                                    50, #Embedding size
                                    input_length=max_review_length) #Number of words in each review
          )

In [36]:
model.output

Embedding Layer Output -
[Batch_Size , Review Length , Embedding_Size]

Flatten the Output

In [37]:
model.add(tf.keras.layers.Flatten())

In [38]:
model.output

Add Dense Layer

In [39]:
model.add(tf.keras.layers.BatchNormalization())

In [40]:
model.output

In [41]:
model.add(tf.keras.layers.Dense(128, activation='relu'))

In [42]:
model.output

In [43]:
model.add(tf.keras.layers.Dropout(0.25))

In [44]:
model.output

Use Dense layer for output layer

In [45]:
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

In [46]:
#Compile the model
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [47]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding (Embedding)       (None, 300, 50)           1500050

 flatten (Flatten)           (None, 15000)             0

 batch_normalization (Batch  (None, 15000)             60000
 Normalization)

 dense (Dense)               (None, 128)               1920128

 dropout (Dropout)           (None, 128)               0

 dense_1 (Dense)             (None, 1)                 129

=================================================================
Total params: 3480307 (13.28 MB)
Trainable params: 3450307 (13.16 MB)
Non-trainable params: 30000 (117.19 KB)
_________________________________________________________________

#### Execute the graph

In [48]:
model.fit(X_train,y_train,
          epochs=5,
          batch_size=32,
          validation_data=(X_test, y_test))

Epoch 1/5
625/625 [==============================] - 26s 41ms/step - loss: 0.5182 - accuracy: 0.7572 - val_loss: 0.3607 - val_accuracy: 0.8662
Epoch 2/5
625/625 [==============================] - 24s 39ms/step - loss: 0.0904 - accuracy: 0.9673 - val_loss: 0.4693 - val_accuracy: 0.8438
Epoch 3/5
625/625 [==============================] - 25s 41ms/step - loss: 0.0540 - accuracy: 0.9805 - val_loss: 0.4921 - val_accuracy: 0.8476
Epoch 4/5
625/625 [==============================] - 26s 41ms/step - loss: 0.0589 - accuracy: 0.9797 - val_loss: 0.4632 - val_accuracy: 0.8526
Epoch 5/5
625/625 [==============================] - 25s 41ms/step - loss: 0.0423 - accuracy: 0.9867 - val_loss: 0.4633 - val_accuracy: 0.8550

### 3. Using Pre-Trained Embeddings

In [49]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.1 kB)
Requirement already satisfied: numpy<2.0,>=1.18.5 in /usr/local/lib/python3.11/dist-packages (from gensim) (1.26.4)
Collecting scipy<1.14.0,>=1.7.0 (from gensim)
  Downloading scipy-1.13.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 4.6 MB/s eta 0:00:00
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.11/dist-packages (from gensim) (7.1.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open>=1.8.1->gensim) (1.14.1)
Downloading gensim-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 78.0 MB/s eta 0:00:00
Downloading scipy-1.13.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 28.0 MB/s eta 0:00:00
Installing collected packages: scipy, gensim
  Attempting uninstall: scipy
    Found existing installation: scipy 1.14.1
    Uninstalling scipy-1.14.1:
      Successfully uninstalled scipy-1.14.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jax 0.5.2 requires ml_dtypes>=0.4.0, but you have ml-dtypes 0.2.0 which is incompatible.
Successfully installed gensim-4.3.3 scipy-1.13.1

In [50]:
import gensim.downloader as api
import numpy as np

Available Word2Vec/Glove Pretained models -> [Link](https://github.com/RaRe-Technologies/gensim-data)

In [51]:
#Load Glove model (similar to Word2Vec)
glove_model = api.load('glove-wiki-gigaword-50')

[==================================================] 100.0% 66.0/66.0MB downloaded

In [52]:
#Size of the model
glove_model.vectors.shape

(400000, 50)

In [ ]:
#glove_model.vocab

In [53]:
glove_model['india']

array([-0.20356 , -0.8707  , -0.19172 ,  0.73862 ,  0.18494 ,  0.14926 ,
        0.48079 , -0.21633 ,  0.72753 , -0.36912 ,  0.13397 , -0.1143  ,
       -0.18075 , -0.64683 , -0.18484 ,  0.83575 ,  0.48179 ,  0.76026 ,
       -0.50381 ,  0.80743 ,  1.2195  ,  0.3459  ,  0.22185 ,  0.31335 ,
        1.2066  , -1.8441  ,  0.14064 , -0.99715 , -1.1402  ,  0.32342 ,
        3.2128  ,  0.42708 ,  0.19504 ,  0.80113 ,  0.38555 , -0.12568 ,
       -0.26533 ,  0.055264, -1.1557  ,  0.16836 , -0.82228 ,  0.20394 ,
        0.089235, -0.60125 , -0.032878,  1.3735  , -0.51661 ,  0.29611 ,
        0.23951 , -1.3801  ], dtype=float32)

In [54]:
#Initialize embedding matrix for our dataset with 30000+1 rows (1 for padding word)
#and 50 columns (as embedding size is 50)
embedding_matrix = np.zeros((desired_vocab_size + 1, 50))

In [55]:
embedding_matrix.shape

(30001, 50)

In [56]:
embedding_matrix[200]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#t.word_index.items()

In [57]:
words_found = 0
for word, i in sorted(t.word_index.items(),key=lambda x:x[1]):
    if i > (desired_vocab_size+1):
        break
    try:
        embedding_vector = glove_model[word] #Reading word's embedding from Glove model for a given word
        embedding_matrix[i] = embedding_vector
        words_found += 1
    except:
        pass

In [58]:
words_found

27682

In [59]:
embedding_matrix[1]

array([ 4.18000013e-01,  2.49679998e-01, -4.12420005e-01,  1.21699996e-01,
        3.45270008e-01, -4.44569997e-02, -4.96879995e-01, -1.78619996e-01,
       -6.60229998e-04, -6.56599998e-01,  2.78430015e-01, -1.47670001e-01,
       -5.56770027e-01,  1.46579996e-01, -9.50950012e-03,  1.16579998e-02,
        1.02040000e-01, -1.27920002e-01, -8.44299972e-01, -1.21809997e-01,
       -1.68009996e-02, -3.32789987e-01, -1.55200005e-01, -2.31309995e-01,
       -1.91809997e-01, -1.88230002e+00, -7.67459989e-01,  9.90509987e-02,
       -4.21249986e-01, -1.95260003e-01,  4.00710011e+00, -1.85939997e-01,
       -5.22870004e-01, -3.16810012e-01,  5.92130003e-04,  7.44489999e-03,
        1.77780002e-01, -1.58969998e-01,  1.20409997e-02, -5.42230010e-02,
       -2.98709989e-01, -1.57490000e-01, -3.47579986e-01, -4.56370004e-02,
       -4.42510009e-01,  1.87849998e-01,  2.78489990e-03, -1.84110001e-01,
       -1.15139998e-01, -7.85809994e-01])

#### Building a model using Pre-Trained embeddings

In [60]:
#Initialize model
tf.keras.backend.clear_session()
model = tf.keras.Sequential()

In [61]:
model.add(tf.keras.layers.Embedding(desired_vocab_size + 1, #Vocablury size
                                    50, #Embedding size
                                    weights=[embedding_matrix],
                                    trainable=False,
                                    input_length=max_review_length) #Number of words in each review
          )

In [62]:
model.output

In [63]:
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dropout(0.25))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

In [64]:
#Compile the model
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [65]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding (Embedding)       (None, 300, 50)           1500050

 flatten (Flatten)           (None, 15000)             0

 batch_normalization (Batch  (None, 15000)             60000
 Normalization)

 dense (Dense)               (None, 128)               1920128

 dropout (Dropout)           (None, 128)               0

 dense_1 (Dense)             (None, 1)                 129

=================================================================
Total params: 3480307 (13.28 MB)
Trainable params: 1950257 (7.44 MB)
Non-trainable params: 1530050 (5.84 MB)
_________________________________________________________________

In [66]:
model.fit(X_train,y_train,
          epochs=5,
          batch_size=32,
          validation_data=(X_test, y_test))

Epoch 1/5
625/625 [==============================] - 17s 26ms/step - loss: 0.8040 - accuracy: 0.6534 - val_loss: 0.5740 - val_accuracy: 0.7032
Epoch 2/5
625/625 [==============================] - 16s 26ms/step - loss: 0.4002 - accuracy: 0.8217 - val_loss: 0.6271 - val_accuracy: 0.6928
Epoch 3/5
625/625 [==============================] - 18s 29ms/step - loss: 0.2548 - accuracy: 0.8928 - val_loss: 0.7533 - val_accuracy: 0.6828
Epoch 4/5
625/625 [==============================] - 17s 27ms/step - loss: 0.1747 - accuracy: 0.9305 - val_loss: 0.8413 - val_accuracy: 0.6838
Epoch 5/5
625/625 [==============================] - 17s 27ms/step - loss: 0.1362 - accuracy: 0.9473 - val_loss: 0.9853 - val_accuracy: 0.6888

### 4. Using CNN

### Using Pre-Trained Embeddings

Available Word2Vec/Glove Pretained models -> [Link](https://github.com/RaRe-Technologies/gensim-data)

In [67]:
#Initialize model
tf.keras.backend.clear_session()
model = tf.keras.Sequential()

In [68]:
model.add(tf.keras.layers.Embedding(desired_vocab_size + 1, #Vocablury size
                                    50, #Embedding size
                                    weights=[embedding_matrix],
                                    trainable=False,
                                    input_length=max_review_length) #Number of words in each review
          )

In [69]:
model.add(tf.keras.layers.BatchNormalization())

In [70]:
model.output

In [71]:
#Replace dense with Conv
model.add(tf.keras.layers.Conv1D(128,
                                 (3),
                                 activation='relu'))

In [72]:
model.output

In [73]:
model.add(tf.keras.layers.Dropout(0.25))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

In [74]:
#Compile the model
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [75]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding (Embedding)       (None, 300, 50)           1500050

 batch_normalization (Batch  (None, 300, 50)           200
 Normalization)

 conv1d (Conv1D)             (None, 298, 128)          19328

 dropout (Dropout)           (None, 298, 128)          0

 flatten (Flatten)           (None, 38144)             0

 dense (Dense)               (None, 1)                 38145

=================================================================
Total params: 1557723 (5.94 MB)
Trainable params: 57573 (224.89 KB)
Non-trainable params: 1500150 (5.72 MB)
_________________________________________________________________

In [76]:
model.fit(X_train,y_train,
          epochs=5,
          batch_size=32,
          validation_data=(X_test, y_test))

Epoch 1/5
625/625 [==============================] - 26s 40ms/step - loss: 0.6535 - accuracy: 0.6906 - val_loss: 0.5462 - val_accuracy: 0.7470
Epoch 2/5
625/625 [==============================] - 25s 40ms/step - loss: 0.4014 - accuracy: 0.8253 - val_loss: 0.4863 - val_accuracy: 0.7820
Epoch 3/5
625/625 [==============================] - 24s 38ms/step - loss: 0.3022 - accuracy: 0.8727 - val_loss: 0.5670 - val_accuracy: 0.7646
Epoch 4/5
625/625 [==============================] - 25s 40ms/step - loss: 0.2405 - accuracy: 0.8989 - val_loss: 0.6438 - val_accuracy: 0.7688
Epoch 5/5
625/625 [==============================] - 25s 40ms/step - loss: 0.1985 - accuracy: 0.9216 - val_loss: 0.5858 - val_accuracy: 0.7922

### 5. With Simple RNN

In [77]:
#Initialize model
tf.keras.backend.clear_session()
model = tf.keras.Sequential()

In [78]:
model.add(tf.keras.layers.Embedding(desired_vocab_size + 1, #Vocablury size
                                    50, #Embedding size
                                    weights=[embedding_matrix],
                                    trainable=False,
                                    input_length=max_review_length) #Number of words in each review
          )

In [79]:
model.output

#### Add Simple RNN layer

In [80]:
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.SimpleRNN(128,
                                    activation='relu')) #RNN State - size of memory

In [81]:
model.output

In [82]:
model.add(tf.keras.layers.Dropout(0.25))

#### Output layer

In [83]:
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))

In [84]:
#Compile the model
model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy'])

In [85]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding (Embedding)       (None, 300, 50)           1500050

 batch_normalization (Batch  (None, 300, 50)           200
 Normalization)

 simple_rnn (SimpleRNN)      (None, 128)               22912

 dropout (Dropout)           (None, 128)               0

 dense (Dense)               (None, 1)                 129

=================================================================
Total params: 1523291 (5.81 MB)
Trainable params: 23141 (90.39 KB)
Non-trainable params: 1500150 (5.72 MB)
_________________________________________________________________

In [86]:
model.fit(X_train,y_train,
          epochs=5,
          batch_size=32,
          validation_data=(X_test, y_test))

Epoch 1/5
625/625 [==============================] - 57s 89ms/step - loss: 0.7288 - accuracy: 0.5369 - val_loss: 0.6773 - val_accuracy: 0.5780
Epoch 2/5
625/625 [==============================] - 52s 84ms/step - loss: 0.6800 - accuracy: 0.5742 - val_loss: 0.6670 - val_accuracy: 0.5908
Epoch 3/5
625/625 [==============================] - 53s 84ms/step - loss: 0.6670 - accuracy: 0.5897 - val_loss: 0.6595 - val_accuracy: 0.5994
Epoch 4/5
625/625 [==============================] - 49s 79ms/step - loss: 0.6542 - accuracy: 0.6105 - val_loss: 0.6478 - val_accuracy: 0.6182
Epoch 5/5
625/625 [==============================] - 51s 81ms/step - loss: 0.6323 - accuracy: 0.6457 - val_loss: 0.7428 - val_accuracy: 0.5248

### 6. Using LSTM

In [87]:
#Initialize model
tf.keras.backend.clear_session()
model = tf.keras.Sequential()

In [88]:
model.add(tf.keras.layers.Embedding(desired_vocab_size + 1, #Vocablury size
                                    50, #Embedding size
                                    weights=[embedding_matrix],
                                    trainable=False,
                                    input_length=max_review_length) #Number of words in each review
          )

In [89]:
model.output

In [90]:
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.LSTM(128)) #RNN State - size of memory

In [91]:
model.output

In [92]:
model.add(tf.keras.layers.Dropout(0.25))

In [93]:
#Output
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))

In [94]:
#Compile the model
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [95]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding (Embedding)       (None, 300, 50)           1500050

 batch_normalization (Batch  (None, 300, 50)           200
 Normalization)

 lstm (LSTM)                 (None, 128)               91648

 dropout (Dropout)           (None, 128)               0

 dense (Dense)               (None, 1)                 129

=================================================================
Total params: 1592027 (6.07 MB)
Trainable params: 91877 (358.89 KB)
Non-trainable params: 1500150 (5.72 MB)
_________________________________________________________________

In [ ]:
model.fit(X_train,y_train,
          epochs=5,
          batch_size=32,
          validation_data=(X_test, y_test))

Epoch 1/5
625/625 [==============================] - 214s 339ms/step - loss: 0.6272 - accuracy: 0.6512 - val_loss: 0.6644 - val_accuracy: 0.5894
Epoch 2/5
625/625 [==============================] - 205s 329ms/step - loss: 0.5265 - accuracy: 0.7276 - val_loss: 0.4789 - val_accuracy: 0.7618
Epoch 3/5
625/625 [==============================] - 204s 327ms/step - loss: 0.4136 - accuracy: 0.8130 - val_loss: 0.3866 - val_accuracy: 0.8296
Epoch 4/5
121/625 [====>.........................] - ETA: 2:38 - loss: 0.3771 - accuracy: 0.8373

In [ ]:
model.fit(X_train,y_train,
          epochs=10,
          initial_epoch=5,
          batch_size=32,
          validation_data=(X_test, y_test))

In [ ]:
model.fit(X_train,y_train,
          epochs=30,
          initial_epoch=10,
          batch_size=32,
          validation_data=(X_test, y_test))